# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Firebase CI

on:
  push:
    branches: [ "publish" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Cache builds
      id: cache-builds
      uses: actions/cache@v3
      with:
        path: dist
        key: ${{ runner.os }}-dist
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive Dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Dist
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      # TODO: Change this before production
      # - name: Depoy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy --only hosting
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  get-new-blogs: 
    needs: deploy
    runs-on: ubuntu-latest
    outputs: 
      # new-blogs: ${{ steps.new-blogs.outputs.newblogs }}
      new-blogs: ${{ steps.changed-files.outputs.added_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
          files: |
            src/pages/posts/**/*.mdx
      - name: List of new blogs
        id: new-blogs
        run: |
          echo ${{ steps.changed-files.outputs.added_files }}
          # newblogs=()
          # for file in ${{ steps.changed-files.outputs.added_files }}; do
          #   newblogs+=(https://shubham.codes${file:9:-4})
          # done
          # newblogs=$(echo "${newblogs[@]}" | xargs | sed -e 's/ /, /g')
          # echo "newblogs=${newblogs}"
          # echo "newblogs=${newblogs}" >> $GITHUB_OUTPUT
  publish-social:
    needs: get-new-blogs
    runs-on: ubuntu-latest 
    # if: ${{ needs.get-new-blogs.outputs.any-changed == true }} 
    strategy: 
      matrix: 
        blog: ${{ fromJson(needs.get-new-blogs.outputs.new-blogs) }}
    steps:
      - name: Notify on Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ matrix.blog }}
            