# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PR

on:
  pull_request:
    branches: [ "publish" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Cache builds
      id: cache-builds
      uses: actions/cache@v3
      with:
        path: dist
        key: ${{ runner.os }}-dist
    - run: npm ci
    - run: npm run build --if-present
    - name: Archive Dist
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist
